### ISSUE TITLE
Failed to authenticate the request error

### ISSUE THREAD

**Issue by rboorgapally** [Azure/azure-sdk-for-node#1365] opened 2014-12-27 23:15 UTC
Hi, I am getting the following error:

Error: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.

The subscription Id and the pm file work correctly in python sdk. But when it comes to node sdk, I got the above error. I am using the following code:

var auth = new azure.CertificateCloudCredentials({
                        subscriptionId:"3fec5be7-3873-45ca-b19d-blahblah",
                        pem:fs.readFileSync("/home/blah/blah/blah/azure.pem").toString()
});

**Comment by xuezhai** [comment] 2015-02-02 19:50
@rboorgapally 

Hi, we cannot reproduce the error. We tested it on Ubuntu. Could you provide more details?

**Comment by markcowl** [comment] 2015-02-27 21:56
@rboorgapally We cannot reproduce, closing for now, please reopen if this recurs and provide more details for repo

**Closed by markcowl** 2015-02-27 21:56 UTC
