### ISSUE TITLE
Error when trying to updateSiteSourceControlSlot()

### ISSUE THREAD

**Issue by adouglas** [Azure/azure-sdk-for-node#1947] opened 2016-10-26 12:53 UTC
when calling updateSiteSourceControlSlot() in my code (coffee script) I am getting the response

`{ Error: {"Code":"NotFound","Message":"Cannot find User with name bd86543d-8895-4f56-cd23-ab2343dc39e.","Target":null,"Details":[{"Message":"Cannot find User with name bd86543d-8895-4f56-cd23-ab2343dc39e."},{"Code":"NotFound"},{"ErrorEntity":{"Code":"NotFound","Message":"Cannot find User with name bd86543d-8895-4f56-cd23-ab2343dc39e.","ExtendedCode":"51004","MessageTemplate":"Cannot find {0} with name {1}.","Parameters":["User","bd86543d-8895-4f56-cd23-ab2343dc39e"],"InnerErrors":null}}],"Innererror":null}`

My code looks like this;

```
class AzureDeploy
  _newSiteSlot: (azureClientId, azureSecret, azureDomain, azureSubscriptionId,     azureResourceGroupName, webSiteSlotTemplate, azureWebSiteName, azureWebSiteSlot,     deployRepoUrl, deployBranch, deployNoop, siteConfig, cb) ->
logger.info 'Logging in to Azure (REST)'

msRestAzure.loginWithServicePrincipalSecret azureClientId, azureSecret, azureDomain, (err, credentials) =>
  if err?
      logger.error 'Error Logging in to Azure (REST)'
      logger.error err
      cb(err)
      return
  logger.info 'Logged in to Azure (REST)'
  client = new webSiteManagementClient(credentials, @azureSubscriptionId)

  siteSourceControl =
    id: "/subscriptions/#{@azureSubscriptionId}/resourceGroups/#{azureResourceGroupName}/providers/Microsoft.Web/sites/#{azureWebSiteName}/slots/#{azureWebSiteSlot}/sourcecontrols/web"
    name: azureWebSiteSlot,
    location: 'North Europe',
    type: 'Microsoft.Web/sites/sourcecontrols',
    repoUrl: deployRepoUrl,
    branch: deployBranch,
    isManualIntegration: true,
    deploymentRollbackEnabled: false,
    isMercurial: false

  logger.info "Updating app scm settings (#{azureResourceGroupName}, #{azureWebSiteName}, #{azureWebSiteSlot}, #{azureWebSiteSlot}, #{deployRepoUrl}, #{deployBranch})"

  client.sites.updateSiteSourceControlSlot azureResourceGroupName, azureWebSiteName, siteSourceControl, azureWebSiteSlot, null, (err, result, request, response) =>
    if err?
       logger.error "App scm settings update failed (#{azureResourceGroupName}, #{azureWebSiteName}, #{azureWebSiteSlot}, #{azureWebSiteSlot}, #{deployRepoUrl}, #{deployBranch})"
       cb(err)
       return

    logger.info "App scm settings updated successfully (#{azureResourceGroupName}, #{azureWebSiteName}, #{azureWebSiteSlot}, #{azureWebSiteSlot}, #{deployRepoUrl}, #{deployBranch})"`
```

I have no problem creating webapps or running listSiteAppSettingsSlot() or update.

**Comment by adouglas** [comment] 2016-10-30 10:38
Please note, this happens even if I only try to log in and call client.sites.updateSiteSourceControlSlot on it's own. 

The user name corresponds to the app id of the user I used to log in as

**Comment by amarzavery** [comment] 2016-10-31 22:10
@naveedaz, @ruslany - Can you guys take a look at this issue?

**Comment by naveedaz** [comment] 2016-11-04 18:17
@suwatch Please take a look at this issue. Might be an issue with the backend.

**Comment by adouglas** [comment] 2016-11-13 22:30
Any update on this?

**Comment by suwatch** [comment] 2016-12-01 23:19
@adouglas this is using service principal, correct?

**Comment by adouglas** [comment] 2016-12-01 23:25
@suwatch yes, and using the same details I can create a site slot, update app settings etc.

**Comment by suwatch** [comment] 2016-12-01 23:29
@adouglas you are doing **manual** integration with **private** repo correct?  If so, is repo github or bitbucket?

**Comment by adouglas** [comment] 2016-12-01 23:40
@suwatch it's a manual integration with a private github repo

**Comment by suwatch** [comment] 2016-12-02 00:44
you will need to associate token with the service principal.   

- Goto github and generate a personal token
- User armclient to associate token with your service principal.  See [this](https://github.com/projectKudu/ARMClient/wiki/Update-SourceControlTokens).   I am not sure if you could do the same for x-plat.

**Comment by naveedaz** [comment] 2017-02-09 20:58
@adouglas Did @suwatch's response help. If so please close the issue.

**Closed** 2017-04-04 05:20 UTC
Labels: Websites

**Comment by hidingmode** [comment] 2017-05-04 12:16
what about manual integration with a private bitbucket repo? where do you get the token from bitbucket?

**Comment by amarzavery** [comment] 2017-05-06 03:28
@naveedaz @davidebbo - Can you please respond to the above query?

**Comment by suwatch** [comment] 2017-05-07 05:32
To get an oauth token bitbucket, you need to go to portal and perform continuous integration to any site once.    To be exact, you will only need the oauth dance path which happens when you chose Bitbucket as deployment source.

**Comment by davidebbo** [comment] 2017-05-07 18:19
And to expand on @suwatch's comment, this is something you only need to do one per Azure account. It's then usable on any subscription / Web App.

**Comment by hidingmode** [comment] 2017-05-21 13:55
I am attempting to use the ARM api for .net to deploy a web app with a bitbucket repo as the source and I keep getting the Conflict error like this one
![image](https://cloud.githubusercontent.com/assets/7817101/26284505/3116cf6e-3e67-11e7-9358-9e7c8b407e85.png)
I suspected that it is due to the service principal not having the auth token to bitbucket, so I used armclient to manually set the bitbucket sourcecontrol token the same as the bitbucket token for my user account ([https://github.com/projectKudu/ARMClient/wiki/Update-SourceControlTokens](url))
Despite that, I still have the same error. Any idea what is causing it and what should I do to fix?

**Comment by davidebbo** [comment] 2017-05-21 18:02
@hidingmode that is likely different from the issue above, and also likely not directly related to the use of the SDK.

Please do the following:

- As a test, see if you're able to set this up via portal
- If that works, try via direct ARM call, e.g. using https://resources.azure.com/

Presumably, if you pass the same params as you've been passing, it will fail too. Then report it to https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview, and we'll take it from there. And you'll need to provide more details about how you're calling the API (but not in the forum, not here).

**Comment by davidebbo** [comment] 2017-05-21 22:01
Actually, I'm pretty sure I know what your issue is. The error is "Bitbucket Authorize: Invalid refresh_token", which means you probably didn't set a refresh token. You can see this on https://resources.azure.com/providers/Microsoft.Web/sourcecontrols/Bitbucket. you should have values for token, refreshToken and expirationTime (token secret will be null).

Just do it via portal and look at the values in explorer to see what it should look like.

**Comment by hidingmode** [comment] 2017-05-22 09:15
@davidebbo I know this is not the best place to continue the discussion for my issue, but I didnt know where to raise this issue. Regardless, the conflict error was gone after I changed the repo content to a .net app as a test. So I am pretty sure that it is due to azure not being able to deploy a plain html file. I suggest changing the error message to refer to the deployment log for better details. Even so, if I want to deploy a plain html file, is it simply not possible with azure? I remember azure could do that a couple of years ago.

Also, a seperate question that I have, is it possible to authorize azure to a bitbucket team? Since bitbucket has a section for "OAuth integrated applications" under https&#58;//bitbucket.org/account/user/&lt;team id&gt;/api

**Comment by davidebbo** [comment] 2017-05-22 13:53
I saw this 'Bitbucket Authorize: Invalid refresh_token' is our logs for your app newdeploymentforwebsite16, so I know it was part of the issue is at least some of your attempts.

Please start separate forum threads for the plain html issue (which absolutely should work), and the bitbucket team issue.
