### ISSUE TITLE
Improved API for sovereign clouds

### ISSUE THREAD

**Issue by chrmarti** [Azure/azure-sdk-for-node#3291] opened 2018-08-06 08:20 UTC
Currently to support sovereign clouds, one has to supply a base URI when creating any of the service clients. Since this parameter is optional, it is not immediately obvious that not supplying it will result in code not supporting sovereign clouds (and presumably Azure Stack).

It would be easier and more natural to write code supporting sovereign clouds if the service clients required an environment object to be passed in alongside with the credentials object (and oftentimes a subscription id).

**Comment by amarzavery** [comment] 2018-08-06 16:42
duplicate of #3280

**Closed by amarzavery** 2018-08-06 16:42 UTC
