### ISSUE TITLE
Handle 429 errors from service

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/azure-sdk-for-node#3247] opened 2018-07-26 23:45 UTC
Related to Azure/autorest#2601

**Comment by daschult** [comment] 2018-11-19 17:30
Duplicate of https://github.com/Azure/ms-rest-js/issues/253. We're not going to fix this in the Node.js packages, only in the TypeScript/JavaScript packages.

**Closed by daschult** 2018-11-19 17:30 UTC
