### ISSUE TITLE
403 Insufficient Privileges error received when calling applications.updatePasswordCredentials 

### ISSUE THREAD

**Issue by kaidaguerre** [Azure/azure-sdk-for-node#2363] opened 2017-12-18 12:34 UTC
I am trying to delete Service principle keys. I can achieve this with graph explorer sending a Patch command to the `https://graph.windows.net/.../applications/.../passwordCredentials` endpoint

When I call this, I see the keys for the Application updated to match those I passed into the patch command.

However when I send the same data using `client.applications.updatePasswordCredentials` in the SDK, I get a 403 error (see below for full details). 

I have tried granting the Service Principal I am connecting with all AD and graph rights.

```Patch Error { Error
    at client.pipeline (/home/turbot/turbot/node_modules/azure-graph/lib/operations/applications.js:1306:19)
    at retryCallback (/home/turbot/turbot/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:89:9)
    at retryCallback (/home/turbot/turbot/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/home/turbot/turbot/node_modules/ms-rest/lib/filters/redirectFilter.js:39:9)
    at /home/turbot/turbot/node_modules/ms-rest-azure/lib/filters/rpRegistrationFilter.js:59:14
    at Request.defaultRequest [as _callback] (/home/turbot/turbot/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/home/turbot/turbot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/turbot/turbot/node_modules/request/request.js:1163:10)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/turbot/turbot/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

[message]: undefined,
  statusCode: 403,
  request: 
   { rawResponse: false,
     queryString: {},
     url: 'https://graph.windows.net/0fae5fbb-c4cf-4d04-9e13-a1260e9fd8f8/applications/73e9c5af-d275-4ad7-b71f-becad04b7be9/passwordCredentials?api-version=1.6',
     method: 'PATCH',
     headers: 
      { 'Content-Type': 'application/json; charset=utf-8',
        'x-ms-client-request-id': '98091249-5f4f-4785-95f7-2e9d67fbb725',
        'accept-language': 'en-US',
        'user-agent': 'Node/v8.9.1 (x64-Linux-4.4.0-53-generic) ms-rest/2.2.7 ms-rest-azure/2.4.5 azure-graph/2.2.0 Azure-SDK-For-Node' },
     body: '{"value":[{"startDate":"2017-12-18T11:32:56.147Z","endDate":"2299-12-31T00:00:00.000Z","keyId":"30fbe2b4-bb76-4815-a5fa-0eaf98fae48e"}]}' },
  response: 
   { body: '{"odata.error":{"code":"Authorization_RequestDenied","message":{"lang":"en","value":"Insufficient privileges to complete the operation."}}}',
     headers: 
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-type': 'application/json; odata=minimalmetadata; streaming=true; charset=utf-8',
        expires: '-1',
        server: 'Microsoft-IIS/8.5',
        'ocp-aad-diagnostics-server-name': 'iNQLRKPaViSNJPZgwTkFBErZ9++/HsuTPOY6L+sp4p4=',
        'request-id': '58ab05a5-aa02-4d83-92ab-ed4d3881af04',
        'client-request-id': '2f95e0e8-aa82-470b-ac2f-490821223488',
        'x-ms-dirapi-data-contract-version': '1.6',
        'ocp-aad-session-key': 'Dqu5YMU56a2Vd00HfElkiGGyaAgJUBJ4beMeiGxWwPog12zcc60p37_unyDNTvRKHJD6uhVzvRr-4pRs-hj3_M5QlLLoRvU3bZwhJIRAKcXopgK2F-d8qaIL6bOpHuI8.SNRXz1kBMRkftzh0u9D-6xtPQItn9Lom6toxEudXUQo',
        'x-content-type-options': 'nosniff',
        dataserviceversion: '3.0;',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'access-control-allow-origin': '*',
        'x-aspnet-version': '4.0.30319',
        'x-powered-by': 'ASP.NET, ASP.NET',
        duration: '2993198',
        date: 'Mon, 18 Dec 2017 12:23:18 GMT',
        connection: 'close',
        'content-length': '139' },
     statusCode: 403 },
  code: undefined,
  body: 
   { code: 'Authorization_RequestDenied',
     message: 'Insufficient privileges to complete the operation.' } }
```

**Comment by yugangw-msft** [comment] 2017-12-18 18:49
@kaidaguerre, to confirm, you used a service principal to execute the code using node sdk and got rejected with the error? If yes, what did you do in detail to accomplish `granting the Service Principal I am connecting with all AD and graph rights`? You granted in portal?

**Comment by kaidaguerre** [comment] 2017-12-18 20:28
Hi.

Thanks for your reply.

Correct, we are using a service principle to execute the sdk code.

In order to grant permissions, I used the portal and went to the App Registrations page for the service principle, and selected Required Permissions. I added all Windows Azure Active Directory and Microsoft Graph permissions and selected Grant Permissions.

To verify the permissions had been granted I checked the application in Enterprise Applications and the permissions were shown there

**Comment by yugangw-msft** [comment] 2017-12-18 21:25
Did you create the service principal or someone else created? Also are you a global admin in the tenant?

**Comment by kaidaguerre** [comment] 2017-12-19 09:01
I created the service principle for test purposes. I am a global admin.

**Comment by kaidaguerre** [comment] 2017-12-20 14:52
Hi. Any further thoughts on this one? Thanks...

**Comment by yugangw-msft** [comment] 2017-12-20 17:40
This should work, which I just now double checked. 
I don't have too much suggestions at this point since I can't reproduce it, but some comments here in case they help
1.  Ensure you are indeed using the service principal with the permissions you have granted as a global admin
2. In the portal, you did configure required permissions under `APPLICATION PERMISSIONS` instead of `DELEGATED PERMISSIONS` and you did click the button of `Grant Permissions` to propagate
3. The below is the payload which worked for me. Note I invoked a patch at the level of the application
```bash
msrest.http_logger : Request URL: 'https://graph.windows.net/54826b22-38d6-4fb2-bad9-b7b93axxxxxx/applications/ce48404b-c717-4021-a04c-02e8afdb0b26?api-version=1.6'
msrest.http_logger : Request method: 'PATCH'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'User-Agent': 'python/3.5.3 (Windows-10-10.0.15063-SP0) requests/2.18.4 msrest/0.4.22 msrest_azure/0.4.19 graphrbacmanagementclient/0.31.0 Azure-SDK-For-Python AZURECLI/2.0.24'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Authorization': '*****'
msrest.http_logger :     'CommandName': 'ad sp reset-credentials'
msrest.http_logger :     'x-ms-client-request-id': 'd49adb34-e5ab-11e7-8354-f4b7e2e85440'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Content-Length': '185'
msrest.http_logger : Request body:
msrest.http_logger : {"passwordCredentials": [{"value": "xxxx", "endDate": "2018-12-20T17:33:05.648473Z", "startDate": "2017-12-20T17:33:05.648473Z", "keyId": "2a3d304c-0191-40ab-9496-7fdf5be8dc8a"}]}
msrest.http_logger : Response status: 204
```

**Comment by amarzavery** [comment] 2017-12-20 18:50
I did something different here. I tried to login as me (global admin or as a user (who is also a global admin)

```javascript
var msRestAzure = require('ms-rest-azure');
var graphRbacManagementClient = require('azure-graph');
var tenantId = '<some guid>';
var spObjectId = '<some guid>';
var appObjectId ='<some guid>';
msRestAzure.loginWithUsernamePassword('fooadmin@*******.onmicrosoft.com', '*******', { tokenAudience: 'graph', domain: tenantId }, function (err, credentials, subscriptions) {
  if (err) console.log(err);
  var client = new graphRbacManagementClient(credentials, tenantId);
  client.servicePrincipals.listPasswordCredentials(spObjectId, function (err, result, request, response) {
    if (err) {
      return console.log(err);
    }
    console.log(result);
    result[0].value = '***********'; //set the new value to the password
    client.applications.patch(appObjectId, {passwordCredentials: result}, function (err, res, req, resp) {
      if (err) return console.log(err);
      console.log(res);
    });
  });
 });
```

**Comment by kaidaguerre** [comment] 2017-12-21 11:25
Ok that is good that you have it reproduced - any idea what the issue is?

**Comment by amarzavery** [comment] 2017-12-21 23:26
Ok some more updates.
- One thing I would like to make clear, one cannot login as a ServicePrincipal and then try to update the password or key credentials of the same ServicePrincipal.
- I was able to login as SP1 whom I given access as shown below and also clicked on the grant permissions button as shown in the picture (I am a global admin in the directory)
![screen shot 2017-12-21 at 3 24 22 pm](https://user-images.githubusercontent.com/4521223/34278997-1af4b7f6-e663-11e7-9693-8c2614cd0aa4.png) and then was able to  patch the passwordCredentials of another application in the same directory.

```javascript
var creds = { "passwordCredentials": [{ "startDate": new Date("2017-12-21T22:22:18.350Z"), "keyId": "b8182e93-554f-4bc0-8453-992038b7e186", "endDate": new Date("2018-12-21T22:22:18.350Z"), "value": "********" }] };
client.applications.patch(objectIdOfSpToReset, creds, function (err, res, req, resp) {
    if (err) return console.log(err);
    console.log(res);
  });
```

**Comment by kaidaguerre** [comment] 2017-12-22 17:16
I have now reproduced this issue from a powershell script, and get the same unauthorised error

I am patching a different Application to the SP which is used to login.

[PatchKeys.txt](https://github.com/Azure/azure-sdk-for-node/files/1583081/PatchKeys.txt)

![image](https://user-images.githubusercontent.com/2838960/34306550-b570e3f8-e73b-11e7-9b05-455f6a1a90d3.png)

**Comment by amarzavery** [comment] 2018-01-02 22:53
@kaidaguerre - We were able to find out the problem.
>  For a service principal to be able to update password of another service principal, it needs to
> - be an **_owner_** of that service principal (Today, this happens **only** when you are logged in as a the primary service principal and **created** the **other** service principal )
> - have atleast **4 permissions** from the Windows Azure Active Directory and one needs to **grant permissions** to that sp

I will go step by step.
## Iteration 1
1. We created a service principal (testsp876), set 4 Application Permissions - saved the changes and then clicked on grant permissions (To grant permissions, you must be a global admin user in the tenant).
![image](https://user-images.githubusercontent.com/4521223/34502509-9bbdd7b4-efc8-11e7-97e0-aeed05d3c82b.png)
2. After that we logged in as that service principal (testsp876) and created another service principal(testsp2).
3. Then we tried to update the password credentials of that sp (testsp2) and were able to do that successfully.
4. We could also see testsp876 as the owner of testsp2 in the portal.
![image](https://user-images.githubusercontent.com/4521223/34502631-346c2d3a-efc9-11e7-8cff-bd3fdab9075a.png)
However, there seems to be a bug in the portal. We were not able to manually add any other sp as the owner. It only allowed us adding users (humans) as owner of that sp.
## Iteration 2.
1. We logged in as service principal (testsp876) and then tried to update the password credentials of service principal (foosp45). The only difference is that testsp876 did not create this sp (foosp45). Now we get the 403 insufficient privileges error.

So it looks like, only if SP A created SP B then SP A can update SP B's credentials. In short it needs to be an owner.

Hope that helps.

**Comment by kaidaguerre** [comment] 2018-01-05 09:41
many thanks for that, I appreciate you following it up.

**Comment by amarzavery** [comment] 2018-02-28 00:38
Closing this issue based on the above comments.

**Closed by amarzavery** 2018-02-28 00:38 UTC
Labels: Team
