### ISSUE TITLE
responseFilter parameter not encoded correctly in cognitiveServicesWebSearch

### ISSUE THREAD

**Issue by rykdesjardins** [Azure/azure-sdk-for-node#5149] opened 2020-04-11 06:20 UTC
I was trying to use the `responseFilter` option in the `cognitiveServicesWebSearch` service and noticed I wasn't able to add multiple filters. After reading the code, I [noticed the commas](https://github.com/Azure/azure-sdk-for-node/blob/739be14a071b6aa0da9269857b3678f0bd6b2614/lib/services/cognitiveServicesWebSearch/lib/operations/web.js#L407) were part of the `encodeURIComponent` parameter, turning them into `%2C`. 

The API doesn't seem to decode them, so I instead mapped on each item of the array with `encodeURIComponent`, then join with comma.

I've already opened a PR #5148, but I'm still opening this issue anyways in case you need every PR to close an issue :)

## More details
To add more context, running the following code would query at the wrong URL.

```
webSearchApiClient.web.search('montreal', { responseFilter : ["Webpages,Images,Videos,News"] }).then((result) => {
   // ...
}).catch(err => {
   // ...
});
```

Queries at : `https://api.cognitive.microsoft.com/bing/v7.0/search?mkt=en-us&q=montreal&responseFilter=Webpages%2CImages%2CVideos%2CNews`

Should be : `https://api.cognitive.microsoft.com/bing/v7.0/search?mkt=en-us&q=montreal&responseFilter=Webpages,Images,Videos,News`

The error message I'm getting was : 

> Only these values are allowed: Webpages,Images,Videos,News,SpellSuggestions,entities,places,RelatedSearches,Computation,TimeZone,Translations

## Original error body
```
{"_type": "ErrorResponse", "errors": [{"_type": "Error", "code": "InsufficientAuthorization", "message": "Insufficient authorization to access requested resource.", "moreDetails":"Only these values are allowed: Webpages,Images,Videos,News,SpellSuggestions,entities,places,RelatedSearches,Computation,TimeZone,Translations", "parameter": "responseFilter", "value": "Webpages%2CImages%2CVideos%2CNews" }]}
```

**Comment by qiaozha** [comment] 2020-04-15 06:40
@ramya-rao-a  Is this a data-plane issue.

**Comment by ramya-rao-a** [comment] 2020-04-15 16:45
Thanks @qiaozha 

@rykdesjardins Thanks for reporting and your efforts in creating the PR. Unfortunately, this is an auto-generated library and we can't take manual fixes in for it.

The [azure-cognitiveservices-websearch](https://www.npmjs.com/package/azure-cognitiveservices-websearch) has been replaced with [@azure/cognitiveservices-websearch](https://www.npmjs.com/package/@azure/cognitiveservices-websearch) which I believe has the same issue. See https://github.com/Azure/azure-sdk-for-js/issues/4244

We found the root cause to be in the runtime we are using [@azure/ms-rest-js](https://www.npmjs.com/package/@azure/ms-rest-js) and are currently looking at making fixes there. We will consider if the fix should be backported to [ms-rest](https://www.npmjs.com/package/ms-rest) such that `azure-cognitiveservices-websearch` is fixed as well or have you update to use `azure-cognitiveservices-websearch` instead.

**Comment by ramya-rao-a** [comment] 2020-05-07 19:59
@rykdesjardins, Thanks for your patience!

The issue https://github.com/Azure/azure-sdk-for-js/issues/4244 has been fixed now.
If you can move to use the [@azure/cognitiveservices-websearch](https://www.npmjs.com/package/@azure/cognitiveservices-websearch) package, it should have the fix.

**Closed by ramya-rao-a** 2020-05-07 19:59 UTC
Labels: Bug, Client, Cognitive Services
