### ISSUE TITLE
Typo in KeyVaultCredentials

### ISSUE THREAD

**Issue by kaosaxis** [Azure/azure-sdk-for-node#5138] opened 2020-01-24 00:12 UTC
Not sure if this is the place to log this, you have sooooooo many repositories and it seems they often change at any given moment. So I'll leave it with this repo's team to sort out :D

**Library in question:**
ms-rest-azure
```
{
  "_from": "ms-rest-azure@^2.6.0",
  "_id": "ms-rest-azure@2.6.0",
  "_inBundle": false,
  "_integrity": "sha512-J6386a9krZ4VtU7CRt+Ypgo9RGf8+d3gjMBkH7zbkM4zzkhbbMOYiPRaZ+bHZcfihkKLlktTgA6rjshTjF329A==",
  "_location": "/ms-rest-azure",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "ms-rest-azure@^2.6.0",
    "name": "ms-rest-azure",
    "escapedName": "ms-rest-azure",
    "rawSpec": "^2.6.0",
    "saveSpec": null,
    "fetchSpec": "^2.6.0"
  },
  "_requiredBy": [
    "/azure-keyvault"
  ],
  "_resolved": "https://registry.npmjs.org/ms-rest-azure/-/ms-rest-azure-2.6.0.tgz",
  "_shasum": "2098efec529eecfa0c6e215b69143abcaba12140",
  "_spec": "ms-rest-azure@^2.6.0",
  "_where": "/srv/projects/sandbox/node_modules/azure-keyvault",
  "author": {
    "name": "Microsoft Corporation",
    "email": "azsdkteam@microsoft.com",
    "url": "https://github.com/Azure/azure-sdk-for-node"
  },
  "bugs": {
    "url": "http://github.com/Azure/azure-sdk-for-node/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "adal-node": "^0.1.28",
    "async": "2.6.0",
    "moment": "^2.22.2",
    "ms-rest": "^2.3.2",
    "request": "^2.88.0",
    "uuid": "^3.2.1"
  },
```

**Specific File with potential issue:**
Repository > File with issue > Function in question
ms-rest-azure > index.d.ts > KeyVaultCredentials

**Code block:**
Issue Coordinates: Line 599 col 56
```
/**
 * An object that performs authentication for Key Vault.
 * @class
 * @param {KeyVaultCredentials~authRequest} authenticator  A callback that receives a challenge and returns an authentication token.
 * @param {object} challengeCache A object used to store a previous challenge
 * @param {credentials} credentials - Credentials needed for the client to connect to Azure.
 */
export class KeyVaultCredentials implements msRest.ServiceClientCredentials {
  constructor( authenticator:  (challenge: object, callback: any) => any, credentials: object );
  /**
   * Signs a request with the Authentication header.
   *
   * @param {webResource} The WebResource to be signed.
   * @param {function(error)}  callback  The callback function.
   * @return {undefined}
   */
  signRequest(webResource: msRest.WebResource, callback: { (err: Error): void }): void;
  createSigningFilter(): (resource: msRest.WebResource, next: Function, callback: msRest.ServiceCallback<any>) => any;
  getCachedChallenge(webResource: msRest.WebResource) : object;
  addChallengeToCache(webResource: msRest.WebResource, chalenge: object) : void;
  handleUnauthorized(webResource: msRest.WebResource, next: Function, err: Error, response: object, body: any, callback: msRest.ServiceCallback<any>) : any;
}
```

**The Issue:**
ms-rest-azure > index.d.ts > KeyVaultCredentials
Line 599 col 56-64 (8 characters)
Possible typo `chalenge` shouldn't this say `challenge`?

![image](https://user-images.githubusercontent.com/56610376/73034704-81fa3c00-3dfa-11ea-9624-a9272a3dfc2c.png)

**Comment by kaosaxis** [comment] 2020-01-24 00:28
Currently present here: https://github.com/Azure/azure-sdk-for-node/blob/9992fa1b709d4f694aff0e865d4a782e6ae74f9c/runtime/ms-rest-azure/index.d.ts

**Comment by kaosaxis** [comment] 2020-01-24 02:15
I just noticed the announcement for the new SDK.
I'll migrate to the newer SDK at
https://github.com/Azure/azure-sdk-for-js

May want to have a bot reply to issues recommending the new SDK.

**Comment by qiaozha** [comment] 2020-02-04 09:37
Thanks for your advice. This deprecation is currently in planing stage. We will take your advice when we start the process.

**Comment by nickzhums** [comment] 2020-02-25 01:13
@kaosaxis thanks for your suggestion! if you have more feedback or issues, you can create an issue on https://github.com/Azure/azure-sdk-for-js

**Comment by ramya-rao-a** [comment] 2020-03-17 03:03
@qiaozha, @nickzhums The source code for the `addChallengeToCache()` method is using the right spelling. See https://github.com/Azure/azure-sdk-for-node/blob/master/runtime/ms-rest-azure/lib/credentials/keyVaultCredentials.js#L183 

The issue is in the typing file index.d.t.s file only which can be fixed by hand. The typing file is used by editors to provide intellisense and other features.

I would suggest that we make the fix and then close this issue

**Comment by qiaozha** [comment] 2020-05-26 05:39
@ramya-rao-a  Can you help me review this PR #5166, I wonder whether we need to release new package for this?

**Comment by ramya-rao-a** [comment] 2020-05-26 06:43
@qiaozha Without a release, the change is not of any use, but on second thoughts, I would not recommend making the change either. 

The `KeyvaultCredentials` from `ms-rest-azure` is used only when using the `azure-keyvault` library.  This package is already deprecated in favor of the new `@azure/keyvault-keys`, `@azure/keyvault-secrets` and `@azure/keyvault-certificates` packages. This does not make any net change to the actual behavior of the package either. So, I don't believe this is worth the effort to test and release the ms-rest-azure package

**Comment by qiaozha** [comment] 2020-05-26 07:08
okay, Then I will close this PR.

**Comment by ramya-rao-a** [comment] 2020-05-26 16:03
Closing issue due to reasons described above.

**Closed by ramya-rao-a** 2020-05-26 16:03 UTC
Labels: needs-triage
