### ISSUE TITLE
KeyVault - set Secret getting 403

### ISSUE THREAD

**Issue by jnystrom** [Azure/azure-sdk-for-node#1932] opened 2016-10-14 21:19 UTC
The Authentication seems to be working (using the sample), but when I call the `client.setSecret` I am getting a 403.  I have registered an app in Azure AD, added a key that does not expire, added the clientId and value of the key and the URI of my key vault to my app (same as the sample).  I have also run the Powershell script to add the principal to the key vault in azure (and I can see it in the portal).  This principal is set to allow ALL permissions for secrets.  I am at a loss...any help?

**Comment by amarzavery** [comment] 2016-10-14 22:06
@pomortaz - Can you take a look at this issue?

**Comment by jnystrom** [comment] 2016-10-14 22:11
Any help I can provide, let me know!  I have been banging my head on this for an entire day, and not sure what I am doing wrong.  I can send you whatever you need.  I am able to add secrets via Azure power shell, but I know that is using my user, and not the application info.  I did link my app to the key vault using the `Set-AzureRmKeyVaultAccessPolicy -VaultName <name> -ObjectId <ObjectId of my app in Azure AD> -PermissionsToSecrets All -ResourceGroup <group name>`.
<img width="950" alt="screen shot 2016-10-14 at 6 09 02 pm" src="https://cloud.githubusercontent.com/assets/1293142/19404140/abff6220-9239-11e6-9d05-e5f8f4c34c1e.png">

**Comment by jnystrom** [comment] 2016-10-14 22:23
Code:
```
const co = require('co');
const KeyVault = require('azure-KeyVault');
const AuthenticationContext = require('adal-node').AuthenticationContext;

function AzureKeyVaultService(config) {
    const cliendId = '<clientid from azure AD app registration';
    const clientSecret = '<client secret from Azure AD app registration Key>';
    const vaultUri = 'https://<vault name>.vault.azure.net/';

    const credentials = new KeyVault.KeyVaultCredentials(authenticator);
    const client = new KeyVault.KeyVaultClient(credentials);

    return {
        addSecret: addSecret,
        getSecret: getSecret,
    }


    function addSecret(id, secret) {
        return new Promise((resolve, reject) => {
            client.setSecret(vaultUri, id, secret, null,
                (err, secretBundle) => {
                    if (err) {
                        
                        return reject(err);
                    } else {
                        console.log('secretBundle:', secretBundle);
                        
                        return resolve(secretBundle);
                    }
                });
        })
    }

    function getSecret(id) {

    }

    function authenticator(challenge, callback) {
        const context = new AuthenticationContext(challenge.authorization);
        return context.acquireTokenWithClientCredentials(challenge.resource, cliendId, clientSecret,
            (err, tokenResponse) => {
                if (err) {
                    throw err;
                } else {
                    const authorizationValue = tokenResponse.tokenType +
                        ' ' + tokenResponse.accessToken;

                    return callback(null, authorizationValue);
                }
            });
    }


}

module.exports = AzureKeyVaultService;

////////////////////////////////////
// CALLING FROM ANOTHER FILE
///////////////////////////////////

....
function addUserReservationCreds(req, res) {
        co(function*() {
            yield keyVaultService.addSecret('test', 'testVal');
        });
    }
...

```

**Comment by pomortaz** [comment] 2016-10-14 22:47
If there were an issue with authentication you would get 401, but since you get 403, it looks like you have not set the vault access permission right. Can you please make sure the object ID that you have set the permissions for belongs to the app you use for authentication. You can use Get-AzureRmADServicePrincipal to confirm.

**Comment by jnystrom** [comment] 2016-10-14 22:58
I am not authorizong the web app, I am just using the appID and key value from the app registered in azure AD.

Get Outlook for iOS




On Fri, Oct 14, 2016 at 6:47 PM -0400, "Pooneh Mortazavi" <notifications@github.com> wrote:





If there were an issue with authentication you would get 401, but since you get 403, it looks like you have not set the vault access permission right. Can you please make sure the object ID that you have set the permissions for belongs to the app you use for authentication. You can use Get-AzureRmADServicePrincipal to confirm.

**Comment by pomortaz** [comment] 2016-10-14 23:02
Oh, so that's probably the problem. You need to give the app permission to access your vault using the command you shared earlier.
Set-AzureRmKeyVaultAccessPolicy -VaultName <name> -ObjectId <ObjectId of my app in Azure AD> -PermissionsToSecrets All -ResourceGroup <group name>

**Comment by jnystrom** [comment] 2016-10-14 23:08
I registered an app with azure ad, the app is not in azure(run in it locally), with the power she'll command i told you about, and that you referenced.  You can see the image above that shows the principal that was created.  I should not have to run the app in azure for this to all work, should I ?

**Comment by jnystrom** [comment] 2016-10-14 23:24
Here is a look at the required permissions for the app that is registered in AZ AD:

<img width="913" alt="screen shot 2016-10-14 at 7 23 02 pm" src="https://cloud.githubusercontent.com/assets/1293142/19405271/bc2ed90a-9243-11e6-9de8-3768840b5599.png">

**Comment by pomortaz** [comment] 2016-10-14 23:35
@karlaugsten can you also please take a look?

@jnystrom no, you don't need to run the app in Azure. 
Ok. Let's take a step back. Follow these steps to make sure you have set the right permissions. In PowerShell follow these steps:
1. `Get-AzureRmKeyVault -VaultName <vault-name>` and look at the list of object IDs
2. ` Get-AzureRmADServicePrincipal -ObjectId <object-id>` and verify that it belong to the app dev-intercept-service.
Let me know what you observe.

**Comment by karlaugsten** [comment] 2016-10-14 23:54
Hey @jnystrom, it looks to me like you have added the objectId of your application. You should instead create a service principal for the application (New-AzureRmADServicePrincipal -ApplicationId <app_id>) and add the objectId of your service principal to the access policy. 
This seems to be a bug in our powershell that you are allowed to even do that, thanks!

**Comment by jnystrom** [comment] 2016-10-14 23:59
You looked at the initial command I sent?  I set the valuation name and set the objective of the app, is that not correct?

**Comment by pomortaz** [comment] 2016-10-15 00:12
@jnystrom the command is correct but the object ID that is provided belongs to an application and not its service principal. The application ID is used for authentication and its service principal receives the permission to access your vault. Sorry I know its confusing. 

Take a look at this sample code to see how to [create application and service principal](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/KeyVault/Microsoft.Azure.KeyVault.Samples/scripts/GetAppConfigSettings.ps1#L53-L62) and [give permission to service principal](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/KeyVault/Microsoft.Azure.KeyVault.Samples/scripts/GetAppConfigSettings.ps1#L96-L100). If you follow that, you could get your problem solved easily. :)

You may not have a service principal created for your application yet. If so, create that first and then use the object ID of the service principal to authorize access for the application.

**Comment by jnystrom** [comment] 2016-10-15 00:36
THANK YOU!  You were absolutely correct, I did not get that from any of docs I read.  I cannot thank you enough for your help!

**Comment by amarzavery** [comment] 2016-10-15 00:37
@jnystrom - Active Directory has this concept of application and service-principal. Here service-principal is a wrapper on top of the application. One can create n service-principals on an application. 
Both of them (service-principal and application) have objectId and applicationId. KeyVault expects the customer to provide the objectId of the service-principal (the wrapper).

We have tried to camouflage these details in powershell and cross platform CLI by keeping this simple when you create an SP. The CLI/Powershell creates an application for you underneath.

You can create and login as an SP using the **CLI** in 3 simple steps. You can follow the instructions [here]
(https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md#2-via-xplatcli-in-3-simple-steps).

If you feel you don't want to install any other tools, then we have a simple script to create an sp using the node sdk. You can find it over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/ServicePrincipal/spCreate.js).

**Comment by amarzavery** [comment] 2016-10-15 00:40
The documentation of the model says that - https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/keyVaultManagement/lib/models/accessPolicyEntry.js#L25
```
* @member {uuid} objectId The object ID of a user, service principal or

 * security group in the Azure Active Directory tenant for the vault. The

 * object ID must be unique for the list of access policies.
```

But it's buried several layers underneath. 

> We should highlight this in the operation and also in the sample to make it very clear for the customer

**Comment by jnystrom** [comment] 2016-10-15 00:50
I think part of my problem is I did most of the configuration through the azure portal, and it looked like I could do all of the config through it, but must have missed some of it.  I had really hoped I could do it all via the portal, configure it once, and not have to touch it again, but that did not seem possible.

**Comment by thenewwazoo** [comment] 2016-10-20 16:49
I think one problem here is that when you create an Application in the portal, it shows the Application's objectId in the UI, and not the Service Principal's. If you're not already aware of the App/SP distinction, it's very easy to c&p the wrong objectId.

**Comment by amarzavery** [comment] 2016-10-21 04:43
Looks like the issue is resolved hence closing it.

**Closed by amarzavery** 2016-10-21 04:43 UTC
Labels: KeyVault

**Comment by vikas-rb15** [comment] 2018-03-19 13:45
https://www.youtube.com/watch?v=cdoY_pnqPiA go through the link to know more. He has give all the details how to create secret and make use of it

**Comment by ledbutter** [comment] 2019-04-17 12:45
I was running into a very similar issue: we were trying to access a key vault via a Azure DevOps Pipelines service connection (i.e. service principal). Things we validated:
 * The app had `user_impersonate` API access to the key vault
 * The app (represented by the object ID of the associated service principal) had key Get, Create, List permissions

What finally resolved it was adding key vault access via the "name" of the app account, which was the same as the application id:
`Set-AzureRmKeyVaultAccessPolicy -VaultName '[VAULT]' -ServicePrincipalName [GUID] -PermissionsToKeys Get, Create, List, Update`

Then everything magically worked. We'd already set the key access policy for the app by its object id, but that didn't resolve it.
