### ISSUE TITLE
`azureRegion cannot be null`

### ISSUE THREAD

**Issue by catcher-in-the-try** [Azure/azure-sdk-for-node#4143] opened 2018-11-20 10:30 UTC
I am trying to use the code for Computer Vision from here:

```js
const { CognitiveServicesCredentials } = require('ms-rest-azure');
 
// Creating the Cognitive Services credentials
// This requires a key corresponding to the service being used (i.e. text-analytics, etc)
let credentials = new CognitiveServicesCredentials('MY LICENSE KEY FROM AZURE PORTAL');

const vision = require('azure-cognitiveservices-vision');
 
let client = new vision.ComputerVisionAPIClient(credentials);
let fileStream = fs.createReadStream('pathToSomeImage.jpg');
client.analyzeImageInStreamWithHttpOperationResponse(fileStream, {
  visualFeatures: ["Categories", "Tags", "Description"]
}).then((response) => {
  console.log(response.body.tags);
  console.log(response.body.description.captions[0]);
}).catch((err) => {
  throw err;
});

```

This produces an error: 

> 'azureRegion' cannot be null.

> computerVisionAPIClient.js:2590:13

There is no mention of any `azureRegion` anywhere in the documentation.

Can you check if this an error in the documentation or in the code? Thanks.

**Comment by scottbell** [comment] 2018-11-20 17:42
This worked for me:
`const region = "westus";
let client = new vision.ComputerVisionAPIClient(credentials, region);`

**Comment by scottbell** [comment] 2018-11-20 17:43
I had to look at the constructor source code of ComputerVisionAPIClient to figure this out though.

**Comment by daschult** [comment] 2018-11-26 20:42
I just merged a PR (https://github.com/Azure/azure-sdk-for-node/pull/4197) that should resolve this problem. Please reopen this issue if the problem isn't fixed.

**Closed** 2018-11-26 20:41 UTC
Labels: Unplanned-Sprint-127, in progress
