### ISSUE TITLE
Cannot delete user via AD Graph API client

### ISSUE THREAD

**Issue by MichaelBurgess** [Azure/azure-sdk-for-node#2264] opened 2017-09-12 13:54 UTC
Hi,

We are trying to delete a user using the Azure AD Graph API from within a Node.js application, but receive the following 403 error:

```
{
  code: 'Authorization_RequestDenied',
  message: 'Insufficient privileges to complete the operation.'
}
```

A snippet of code showing how we connect looks like this:

```coffee
creds = # TokenCloudCredentials containing clientId, clientKey & token etc
tenant = '<OurTenant>'
userId = '<UserIdToDelete>'
client = azure.createGraphManagementClient creds, tenant
client.users.deleteMethod userId, (err, result) ->
  console.log err
  console.log result
```

The HTTP request that the SDK builds looks like this:

```
{
  rawResponse: false,
  queryString: {},
  url: 'https://graph.windows.net/<OurTenant>/users/<UserIdToDelete>?api-version=1.6',
  method: 'DELETE',
  headers: 
  {
    'x-ms-client-request-id': 'f9f162e2-9d4f-4447-8252-97613fd15c61',
    'accept-language': 'en-US',
    'Content-Type': 'application/json; charset=utf-8',
    'user-agent': 'Node/v6.11.2 (x64-Linux-4.4.0-93-generic) ms-rest/2.2.2 ms-rest-azure/2.3.0 azure-graph/2.0.0-preview Azure-SDK-For-Node'
  },
  body: null
}
```

I am able to successfully perform list and get operations from our application using the same code (except with a get API request), e.g.

```coffee
creds = # TokenCloudCredentials containing clientId, clientKey & token etc
tenant = '<OurTenant>'
userId = '<UserIdToDelete>'
client = azure.createGraphManagementClient creds, tenant
client.users.list (err, result) ->
  console.log err
  console.log result
```

We have looked at various help articles and also checked the delegated permissions for our application in the Azure Portal, but cannot seem to get past this issue.

Please could someone advise if this is possible via the Azure AD Graph API -> Users (the fact there is a deleteMethod function on it suggests it is?) and if so, what settings we need to change in code or the Portal to get this working?

Thanks,
Mike.

**Comment by amarzavery** [comment] 2017-09-12 16:27
I assume you are using service-principal for authentication because you mentioned about clientId and clientKey.

Graph is a little special than other Azure Services. You need to provide the tenantId a.k.a domain while authenticating. In the options object you need to specify that the tokenAudience is "graph". That shall get you the correct token with which you can create/get/delete artifacts from your active directory.

Please take a look at the service principal sample over [here](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/graphManagement#login-with-serviceprincipal-and-secret).

The same sample also shows up on npm when you search for the azure-graph package https://www.npmjs.com/package/azure-graph#login-with-serviceprincipal-and-secret

**Comment by MichaelBurgess** [comment] 2017-09-13 15:29
@amarzavery - I haven't had chance to test yet - thanks for the suggestion. I will try soon and let you know how I get on.

**Comment by amarzavery** [comment] 2017-09-13 17:01
Sounds good. Just wanted to make sure that you are unblocked.

**Comment by amarzavery** [comment] 2017-09-20 16:11
closing this issue. please feel free to reopen if the problem persists.

**Closed by amarzavery** 2017-09-20 16:11 UTC

**Comment by amarzavery** [comment] 2017-10-03 18:09
@MichaelBurgess - I just found out that service principal can create/update/get/list users but cannot delete users from a directory. The graph team said that this is by design. Deleting users can be done by a user who is a global administrator or some type of limited administrator. Please refer to my response in this [issue](https://github.com/Azure/azure-sdk-for-node/issues/2280#issuecomment-333929805)
