### ISSUE TITLE
ms-rest-azure depends on moment but does not use it

### ISSUE THREAD

**Issue by alopix** [Azure/azure-sdk-for-node#5157] opened 2020-05-05 07:46 UTC
The ms-rest-azure tool depends on the moment package but does not actively use it.

[Code Search](https://github.com/Azure/azure-sdk-for-node/search?q=path%3A%2Fruntime%2Fms-rest-azure+moment&unscoped_q=path%3A%2Fruntime%2Fms-rest-azure+moment)

Similarly ms-rest uses it to check if something is a `duration` which could probably achieved using a more lightweight library?
[Code Search](https://github.com/Azure/azure-sdk-for-node/search?q=path%3A%2Fruntime%2Fms-rest+moment&unscoped_q=path%3A%2Fruntime%2Fms-rest+moment)

**Comment by qiaozha** [comment] 2020-05-26 03:36
Thanks for reporting this, I will follow up on this.

**Comment by qiaozha** [comment] 2020-06-03 08:37
@ramya-rao-a  Hi Ramya, I found this issue https://github.com/Azure/azure-sdk-for-node/issues/5154 is about the moment package as well. the code referenced moment but actually don't use it. Should we remove the moment dependency and release a new package for azure-arm-resource ?

**Comment by ramya-rao-a** [comment] 2020-06-05 04:51
For ms-rest-azure, we can definitely remove the dependency altogether

@maggiepint What would you recommend as a replacement for `moment.isDuration()`?

@qiaozha, Issue #5154 is slightly different as I believe that is auto generated code. You can either fix the code generator and re-generate the package or remove the unused moment references manually. Since we don't plan to do any further feature work here and therefore no code regeneration in the future, it should be safe to manually change it.

**Comment by ramya-rao-a** [comment] 2020-07-28 06:06
@qiaozha, Can we update `ms-rest-azure` to remove the dependency on `moment` which it does not use?

 @maggiepint What would you recommend as a replacement for `moment.isDuration()`?

**Comment by qiaozha** [comment] 2020-07-28 06:11
> @qiaozha, Can we update `ms-rest-azure` to remove the dependency on `moment` which it does not use?
> 
> @maggiepint What would you recommend as a replacement for `moment.isDuration()`?

I can remove it and I need to release a new ms-rest-azure ?

**Comment by ramya-rao-a** [comment] 2020-07-28 06:16
I don't believe a release is needed as this is not a bug fix. The next time we have a bug fix, the changes can be released together

**Comment by qiaozha** [comment] 2020-07-28 08:04
@ramya-rao-a Okay, then I won't release the package unless there's a request specifically ask for a new release. Can you help review my PR #5188

**Comment by qiaozha** [comment] 2020-09-27 08:16
close it as the PR is merged, issue should be fixed in any next release of ms-rest-azure

**Closed by qiaozha** 2020-09-27 08:16 UTC
