### ISSUE TITLE
BaseResource missing from azure-arm-website definition file

### ISSUE THREAD

**Issue by tvand7093** [Azure/azure-sdk-for-node#2064] opened 2017-02-15 23:42 UTC
I am attempting to use the `azure-arm-website` node package in a typescript project. However, I ran into an issue when compiling my typescript files stating the following: 

```bash
node_modules/azure-arm-website/lib/models/index.d.ts(54,35): error TS2304: Cannot
find name 'BaseResource'.
```

Upon opening the file, sure enough there is no import to the `ms-rest-azure` module. I found that by adding the line below to the index.d.ts file fixes the problem.

```typescript
import { BaseResource } from 'ms-rest-azure';
```
Am I just using the module wrong, or is this a known issue? I haven't been able to find anything about this online so I assume it is a legitimate issue. Here is how I am importing the module into my project:

```typescript
import Models = require('../node_modules/azure-arm-website/lib/models/index');
```

DISCLAIMER: I am new to typescript so if I am just doing things completely wrong, feel free to let me know!

**Comment by balajikris** [comment] 2017-02-16 21:58
@tvand7093 : you are correct in your assessment that the auto-generated `.d.ts` files are indeed out of date and/or incorrect. This is likely because typescript lang underwent major changes and the autogeneration of `.d.ts` files didn't keep up. We are aware of the issue and are working on it. Thanks for the bug report.

@amarzavery : please feel free to expand on my comments.

**Comment by tvand7093** [comment] 2017-02-16 23:11
Thanks for the quick feedback/insight. I think that the idea of a typescript SDK would be fantastic. For the time being, I have just created a small [patch script](https://gist.github.com/tvand7093/12b506dc40515ab724bdb8f4537c2c6c) that I run with npm prior to building the typescript files. In case anyone runs into this issue.

**Comment by balajikris** [comment] 2017-03-02 21:24
I'm collecting a list of issues with the typings file for packages we generate at #2083. I'd like to dupe this bug if there are no objections.

**Comment by balajikris** [comment] 2017-03-02 21:41
closing as dupe of #2083

**Closed by balajikris** 2017-03-02 21:41 UTC
Labels: resolution-duplicate
