### ISSUE TITLE
[Tooling] API typings file is pretty out-of-date

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-sdk-for-node#2061] opened 2017-02-14 22:21 UTC
If you author code using this library within VS Code, the auto-completion that is provided is pretty out-of-date, and doesn't give an accurate impression of what you can achieve:

![image](https://cloud.githubusercontent.com/assets/116461/22952000/2b8bdaa0-f2c0-11e6-925c-89414a5fced4.png)

You can obviously check the docs to understand what the full API surface looks like, but it would be ideal if the (azure typings file)[https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/azure] was maintained along with this library, so that we could help create an amazing authoring experience for users.

I noticed a similar discussion via #1578, which was closed for some reason, so I'd love to re-make the ask, since the community obviously hasn't organically maintained quality here.

**Comment by balajikris** [comment] 2017-02-16 22:43
It isn't simply out of date, but i find some of these don't even build. I tried writing a typescript sample for storage against our generated `.d.ts` files and I had to hand fix 4-5 compilation errors to get it to build. Its likely because that typescript lang underwent a lot of churn and we didn't keep up with it.

Also see #2064

**Comment by balajikris** [comment] 2017-03-02 21:24
I'm collecting a list of issues with the typings file for packages we generate at https://github.com/Azure/azure-sdk-for-node/issues/2083. I'd like to dupe this bug if there are no objections.

**Comment by lostintangent** [comment] 2017-03-02 21:27
Sounds good. Feel free to close this one. Thanks!

**Comment by balajikris** [comment] 2017-03-02 21:40
Closing, as dupe of #2083

**Closed by balajikris** 2017-03-02 21:40 UTC
